---
title       : "Novo PPC - Curso de Música"
subtitle    : Apresentação
author      : Neylson Crepalde
job         : Coordenação
biglogo     : musica_cortado.png
logo        : izabela_logo_branca.png
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [mathjax, quiz, bootstrap, interactive]
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Novo PPC - Curso de Música

A partir de um esforço contínuo e conjunto da PROACAD, coordenação e colegiado do curso, apresentamos os princípios norteadores e resultados obtidos na formulação do novo Projeto Pedagógico do Curso de Licenciatura em Música do Centro Universitário Metodista Izabela Hendrix.

--- .class #docs

## Documentos norteadores

>- Lei de Diretrizes e Bases da Educação Nacional nº 9394/96;

>- Resolução CNE/CP nº2, de 01/07/2015, que “Define as Diretrizes Curriculares Nacionais para a formação inicial em nível superior (cursos de licenciatura, cursos de formação pedagógica para graduados e cursos de segunda licenciatura) e para a formação continuada”

>- Resolução CNE/CES nº2, de 08/03/2004, que aprova as Diretrizes Curriculares Nacionais para os Cursos de Música.

--- .segue .nobackground .dark
## <span class="red">O que mudou?</span>

--- .class #novo
## Principais Novidades

>- Currículo dividido em **módulos**;

>- Profunda revisão das **Práticas Pedagógicas Musicais** sanando defasagem de nosso curso;

>- Melhor adequação à Resolução CNE/CES nº2/2004 quanto à articulação do ensino de música e **humanidades**, especialmente **antropologia**;

>- Adequação à CNE/CP nº2/2015 quanto à **carga horária** e tempo mínimo de integralização;

>- **Produção musical(!!!)**;

>- **Editoração** de partituras;

>- **Projetos Culturais**;

>- **Filosofia da Arte**.

--- .segue .dark
## <span style="color: yellow;">A nova proposta</span>

--- .class #linhas
## Linhas de Formação PDI

>- As linhas de formação previstas no PDI da instituição bem como as habilidades e competências delas derivadas foram contempladas sobretudo no ementário e na criação de novas disciplinas comuns e específicas.

>- As linhas de formação específicas foram readequadas visando adequação com a DCN específica do curso, a "DCN das licenciaturas" e as expectativas do mercado elencadas na pesquisa preliminar.

--- .class #extpesq
## Extensão e Pesquisa

> Novas diretrizes para as ações e projetos de extensão e pesquisa no curso:

> "o curso de licenciatura em música privilegiará ações e projetos de extensão e pesquisa que aliem a prática docente à teoria da educação musical, que se relacionem à prática de música contemporânea ou música popular, que gerem dados sobre a produção cultural em Belo Horizonte e em Minas Gerais e que contribuam para a aproximação da sociedade com o corpo docente e discente."

<span style="color:#B40404;">**A partir da nova matriz, a extensão vinculada à pesquisa terão um papel mais robusto na formação do discente do curso de música!**</span>

--- .class #autonomia
## Autonomia discente

A autonomia discente fica a cargo das disciplinas **Instrumento Harmônico** e das novas disciplinas ofertadas em interface com outros cursos da casa. Além disso, abrimos espaço para duas optativas localizadas na parte central do curso. O aluno poderá cursar disciplinas de Fonoaudiologia, Arquitetura, Direito, Contábeis, Educação Física ou qualquer outro curso de sua escolha.

--- .class #tech
## Tecnologia e adequação ao mercado

O curso está agora mais alinhado às expectativas do mercado proporcionando ao aluno o desenvolvimento de competências relacionadas a tecnologias de gravação e manipulação de áudio bem como conhecimentos sobre a concepção e gestão de uma produção musical.

---.segue .dark #obrigado
## <span style="color:#58ACFA;">Obrigado!</span>

